import { ExamType, Subject } from './types';

// Helper to structure syllabus data
type SyllabusData = {
  [key in Subject]?: {
    class11: Record<string, string[]>; // Chapter -> Topics[]
    class12: Record<string, string[]>; // Chapter -> Topics[]
  };
};

export const SYLLABUS: SyllabusData = {
  [Subject.PHYSICS]: {
    class11: {
      'Units & Measurements': ['Systems of Units', 'SI Units', 'Dimensional Analysis', 'Errors in Measurement', 'Significant Figures'],
      'Motion in a Straight Line': ['Path Length and Displacement', 'Average Velocity and Speed', 'Instantaneous Velocity and Speed', 'Kinematic Equations (Uniform Acceleration)', 'Relative Velocity'],
      'Motion in a Plane': ['Scalars and Vectors', 'Projectile Motion', 'Uniform Circular Motion', 'Relative Velocity in 2D'],
      'Laws of Motion': ['Newton\'s First Law', 'Newton\'s Second Law', 'Newton\'s Third Law', 'Conservation of Momentum', 'Equilibrium of a Particle', 'Friction', 'Circular Motion Dynamics'],
      'Work, Energy & Power': ['Work done by Constant/Variable Force', 'Kinetic Energy & Work-Energy Theorem', 'Potential Energy', 'Conservation of Mechanical Energy', 'Collisions (Elastic & Inelastic)'],
      'System of Particles & Rotational Motion': ['Centre of Mass', 'Torque & Angular Momentum', 'Moment of Inertia', 'Theorems of Perpendicular & Parallel Axes', 'Kinematics of Rotational Motion'],
      'Gravitation': ['Kepler\'s Laws', 'Universal Law of Gravitation', 'Acceleration due to Gravity', 'Gravitational Potential Energy', 'Escape Speed', 'Earth Satellites'],
      'Mechanical Properties of Solids': ['Stress and Strain', 'Hooke\'s Law', 'Young\'s Modulus', 'Elastic Potential Energy'],
      'Mechanical Properties of Fluids': ['Pascal\'s Law', 'Archimedes Principle', 'Bernoulli\'s Principle', 'Viscosity', 'Surface Tension'],
      'Thermal Properties of Matter': ['Thermal Expansion', 'Calorimetry', 'Heat Transfer (Conduction, Convection, Radiation)', 'Newton\'s Law of Cooling'],
      'Thermodynamics': ['Thermal Equilibrium (Zeroth Law)', 'First Law of Thermodynamics', 'Specific Heat Capacity', 'Thermodynamic Processes (Isochoric, Isobaric, Isothermal, Adiabatic)', 'Second Law of Thermodynamics'],
      'Kinetic Theory': ['Ideal Gas Equation', 'Kinetic Theory of Gases', 'Law of Equipartition of Energy', 'Specific Heat Capacity of Gases', 'Mean Free Path'],
      'Oscillations': ['Periodic Motion', 'Simple Harmonic Motion (SHM)', 'Energy in SHM', 'Simple Pendulum', 'Damped & Forced Oscillations'],
      'Waves': ['Transverse & Longitudinal Waves', 'Displacement Relation', 'Speed of Travelling Wave', 'Superposition Principle', 'Standing Waves', 'Beats', 'Doppler Effect'],
    },
    class12: {
      'Electric Charges and Fields': ['Coulomb\'s Law', 'Electric Field & Field Lines', 'Electric Dipole', 'Electric Flux (Gauss\'s Law)', 'Applications of Gauss\'s Law'],
      'Electrostatic Potential and Capacitance': ['Electric Potential', 'Potential due to a Dipole', 'Equipotential Surfaces', 'Capacitors & Capacitance', 'Energy Stored in Capacitor'],
      'Current Electricity': ['Ohm\'s Law', 'Drift Velocity', 'Resistivity & Conductivity', 'Series & Parallel Combination of Resistors', 'Kirchhoff\'s Rules', 'Wheatstone Bridge', 'Potentiometer'],
      'Moving Charges & Magnetism': ['Magnetic Force (Lorentz Force)', 'Motion in a Magnetic Field', 'Biot-Savart Law', 'Ampere\'s Circuital Law', 'Force between Two Parallel Currents', 'Moving Coil Galvanometer'],
      'Magnetism & Matter': ['Bar Magnet as Dipole', 'Earth\'s Magnetism', 'Magnetisation & Magnetic Intensity', 'Magnetic Properties of Materials (Dia, Para, Ferro)'],
      'Electromagnetic Induction': ['Magnetic Flux', 'Faraday\'s Law of Induction', 'Lenz\'s Law', 'Motional EMF', 'Inductance (Self & Mutual)', 'AC Generator'],
      'Alternating Current': ['AC Voltage applied to R, L, C', 'LCR Series Circuit (Phasors)', 'Resonance', 'Power in AC Circuit', 'Transformers'],
      'Electromagnetic Waves': ['Displacement Current', 'Electromagnetic Spectrum', 'Properties of EM Waves'],
      'Ray Optics': ['Reflection of Light', 'Refraction (Snell\'s Law)', 'Total Internal Reflection', 'Refraction at Spherical Surfaces', 'Lenses & Lens Maker\'s Formula', 'Prism', 'Optical Instruments'],
      'Wave Optics': ['Huygens Principle', 'Refraction & Reflection of Plane Waves', 'Interference (Young\'s Double Slit)', 'Diffraction', 'Polarisation'],
    },
  },
  [Subject.CHEMISTRY]: {
    class11: {
      'Some Basic Concepts of Chemistry': ['Mole Concept & Molar Mass', 'Stoichiometry', 'Limiting Reagent', 'Concentration Terms (Molarity, Molality)', 'Empirical & Molecular Formula'],
      'Structure of Atom': ['Bohr\'s Model', 'Quantum Numbers', 'Electronic Configuration', 'Heisenberg\'s Uncertainty Principle', 'Shapes of Orbitals'],
      'Classification of Elements and Periodicity': ['Modern Periodic Law', 'Trends in Physical Properties (Atomic Radius, Ionization Enthalpy)', 'Trends in Chemical Properties', 'Electronegativity'],
      'Chemical Bonding and Molecular Structure': ['Ionic & Covalent Bonding', 'VSEPR Theory', 'Valence Bond Theory', 'Hybridisation', 'Molecular Orbital Theory'],
      'States of Matter': ['Intermolecular Forces', 'Ideal Gas Equation', 'Dalton\'s Law of Partial Pressure', 'Kinetic Molecular Theory', 'Liquefaction of Gases'],
      'Thermodynamics': ['Internal Energy & Enthalpy', 'Hess\'s Law', 'Enthalpy of Different Reactions', 'Spontaneity (Gibbs Energy)', 'Entropy'],
      'Equilibrium': ['Law of Chemical Equilibrium', 'Le Chatelier\'s Principle', 'Ionization of Acids & Bases', 'pH Concept', 'Buffer Solutions', 'Solubility Product'],
      'Redox Reactions': ['Oxidation Number', 'Balancing Redox Reactions', 'Types of Redox Reactions'],
      'Hydrogen': ['Position in Periodic Table', 'Hydrides', 'Water & Heavy Water', 'Hydrogen Peroxide', 'Hydrogen as Fuel'],
      'The s-block Elements': ['Alkali Metals (Group 1)', 'Alkaline Earth Metals (Group 2)', 'Anomalous Properties of Li & Be', 'Important Compounds'],
      'The p-block Elements': ['Group 13 Elements (Boron Family)', 'Group 14 Elements (Carbon Family)', 'Allotropes of Carbon', 'Silicates & Zeolites'],
      'Environmental Chemistry': ['Atmospheric Pollution', 'Water Pollution', 'Soil Pollution', 'Green Chemistry'],
      'Some Basic Principles of Organic Chemistry': ['IUPAC Nomenclature', 'Isomerism', 'Electronic Displacements (Inductive, Resonance, Hyperconjugation)', 'Reaction Intermediates', 'Purification Techniques'],
      'Hydrocarbons': ['Alkanes (Preparation & Properties)', 'Alkenes (Geometrical Isomerism, Markovnikov Rule)', 'Alkynes (Acidic Nature)', 'Aromatic Hydrocarbons (Benzene, Electrophilic Substitution)'],
      'Organic Chemistry: Experimental and Techniques': ['Detection of Elements (Lassaigne\'s Test)', 'Qualitative Analysis', 'Quantitative Analysis'],
    },
    class12: {
      'Solid State': ['Unit Cells & Lattices', 'Packing Efficiency', 'Void Types', 'Imperfections in Solids', 'Electrical & Magnetic Properties'],
      'Solutions': ['Solubility (Henry\'s Law)', 'Raoult\'s Law', 'Colligative Properties', 'Van\'t Hoff Factor'],
      'Electrochemistry': ['Nernst Equation', 'Conductance in Electrolytic Solutions', 'Kohlrausch\'s Law', 'Batteries & Fuel Cells', 'Corrosion'],
      'Chemical Kinetics': ['Rate of Reaction', 'Order & Molecularity', 'Integrated Rate Equations', 'Arrhenius Equation', 'Collision Theory'],
      'Surface Chemistry': ['Adsorption', 'Catalysis', 'Colloids (Classification & Properties)', 'Emulsions'],
      'General Principles & Processes of Isolation of Elements': ['Concentration of Ores', 'Extraction of Crude Metal', 'Refining Techniques', 'Ellingham Diagram'],
      'The p-block Elements': ['Group 15 (Nitrogen Family)', 'Group 16 (Oxygen Family)', 'Group 17 (Halogens)', 'Group 18 (Noble Gases)'],
      'The d- & f-Block Elements': ['Transition Elements (Properties)', 'Lanthanoids', 'Actinoids', 'Potassium Dichromate & Permanganate'],
      'Coordination Compounds': ['Werner\'s Theory', 'Nomenclature', 'Isomerism', 'Valence Bond Theory', 'Crystal Field Theory'],
      'Haloalkanes and Haloarenes': ['Nucleophilic Substitution (SN1 & SN2)', 'Elimination Reactions', 'Reactions of Haloarenes', 'Polyhalogen Compounds'],
      'Alcohols, Phenols and Ethers': ['Preparation & Properties of Alcohols', 'Acidity of Phenols', 'Preparation & Properties of Ethers', 'Williamson Synthesis'],
      'Aldehydes, Ketones and Carboxylic Acids': ['Nucleophilic Addition Reactions', 'Aldol Condensation & Cannizzaro Reaction', 'Oxidation & Reduction', 'Acidity of Carboxylic Acids'],
      'Amines': ['Preparation of Amines', 'Basic Character of Amines', 'Diazonium Salts'],
      'Biomolecules': ['Carbohydrates (Glucose, Fructose)', 'Proteins (Amino Acids, Peptide Bond)', 'Nucleic Acids (DNA, RNA)', 'Vitamins'],
      'Polymers': ['Addition & Condensation Polymerisation', 'Copolymerisation', 'Biodegradable Polymers'],
      'Chemistry in Everyday Life': ['Drugs & their Classification', 'Chemicals in Food', 'Cleansing Agents (Soaps & Detergents)'],
    },
  },
  [Subject.BIOLOGY]: {
    class11: {
      'The Living World': ['Taxonomy & Systematics', 'Taxonomic Categories', 'Taxonomical Aids'],
      'Biological Classification': ['Five Kingdom Classification', 'Monera', 'Protista', 'Fungi', 'Viruses, Viroids & Lichens'],
      'Plant Kingdom': ['Algae', 'Bryophytes', 'Pteridophytes', 'Gymnosperms', 'Angiosperms', 'Plant Life Cycles'],
      'Animal Kingdom': ['Basis of Classification', 'Non-Chordates (Porifera to Hemichordata)', 'Chordates'],
      'Morphology of Flowering Plants': ['Root, Stem, Leaf', 'Inflorescence & Flower', 'Fruit & Seed', 'Families (Fabaceae, Solanaceae, Liliaceae)'],
      'Anatomy of Flowering Plants': ['Tissues (Meristematic & Permanent)', 'Tissue Systems', 'Anatomy of Root, Stem, Leaf', 'Secondary Growth'],
      'Structural Organisation in Animals': ['Animal Tissues', 'Morphology & Anatomy of Frog/Cockroach/Earthworm'],
      'Cell: The Unit of Life': ['Prokaryotic vs Eukaryotic Cells', 'Cell Organelles & Functions', 'Endomembrane System', 'Nucleus'],
      'Biomolecules': ['Carbohydrates, Proteins, Lipids', 'Enzymes (Mechanism & Factors)', 'Nucleic Acids'],
      'Cell Cycle and Cell Division': ['Mitosis', 'Meiosis', 'Significance of Cell Division'],
      'Transport in Plants': ['Water Potential', 'Osmosis & Plasmolysis', 'Transpiration', 'Phloem Transport'],
      'Mineral Nutrition': ['Essential Mineral Elements', 'Deficiency Symptoms', 'Nitrogen Cycle'],
      'Photosynthesis in Higher Plants': ['Light Reaction', 'Electron Transport', 'C3 and C4 Pathways', 'Photorespiration'],
      'Respiration in Plants': ['Glycolysis', 'Fermentation', 'Krebs Cycle', 'Electron Transport System'],
      'Plant Growth and Development': ['Growth Regulators (Auxin, Gibberellin, Cytokinin)', 'Photoperiodism', 'Vernalisation'],
      'Digestion and Absorption': ['Alimentary Canal', 'Digestive Glands', 'Digestion of Food', 'Absorption of Digested Products'],
      'Breathing and Exchange of Gases': ['Respiratory Organs', 'Mechanism of Breathing', 'Transport of Gases', 'Regulation of Respiration'],
      'Body Fluids and Circulation': ['Blood & Lymph', 'Human Circulatory System', 'Cardiac Cycle', 'ECG', 'Double Circulation'],
      'Excretory Products and Their Elimination': ['Modes of Excretion', 'Human Excretory System', 'Urine Formation', 'Regulation of Kidney Function'],
      'Locomotion and Movement': ['Muscle Contraction', 'Skeletal System', 'Joints'],
      'Neural Control and Coordination': ['Neuron Structure', 'Central Nervous System', 'Reflex Action', 'Sensory Perception (Eye & Ear)'],
      'Chemical Coordination and Integration': ['Endocrine Glands & Hormones', 'Mechanism of Hormone Action'],
    },
    class12: {
      'Reproduction in Organisms': ['Asexual Reproduction', 'Sexual Reproduction'],
      'Sexual Reproduction in Flowering Plants': ['Flower Structure', 'Pollination', 'Double Fertilization', 'Post-fertilization Events'],
      'Human Reproduction': ['Male & Female Reproductive Systems', 'Gametogenesis', 'Menstrual Cycle', 'Fertilization & Implantation', 'Parturition & Lactation'],
      'Reproductive Health': ['Reproductive Health Problems', 'Population Stabilization', 'Birth Control Methods', 'Infertility & ART'],
      'Principles of Inheritance and Variation': ['Mendel\'s Laws', 'Incomplete Dominance & Co-dominance', 'Chromosomal Theory of Inheritance', 'Sex Determination', 'Genetic Disorders'],
      'Molecular Basis of Inheritance': ['Structure of DNA', 'Replication', 'Transcription', 'Genetic Code', 'Translation', 'Lac Operon', 'DNA Fingerprinting'],
      'Evolution': ['Origin of Life', 'Evidences for Evolution', 'Darwinism', 'Modern Synthetic Theory', 'Human Evolution'],
      'Human Health and Disease': ['Common Infectious Diseases', 'Immunity (Innate & Acquired)', 'AIDS & Cancer', 'Drugs and Alcohol Abuse'],
      'Strategies for Enhancement in Food Production': ['Animal Husbandry', 'Plant Breeding', 'Single Cell Protein', 'Tissue Culture'],
      'Microbes in Human Welfare': ['Microbes in Household Products', 'Industrial Products', 'Sewage Treatment', 'Biocontrol Agents', 'Biofertilizers'],
      'Biotechnology: Principles and Processes': ['Restriction Enzymes', 'Cloning Vectors', 'PCR', 'Processes of R-DNA Technology'],
      'Biotechnology and Its Applications': ['Applications in Agriculture (Bt Cotton)', 'Applications in Medicine (Insulin, Gene Therapy)', 'Transgenic Animals', 'Ethical Issues'],
      'Organisms and Populations': ['Abiotic Factors', 'Population Attributes', 'Population Interactions'],
      'Ecosystem': ['Ecosystem Structure', 'Energy Flow', 'Ecological Pyramids', 'Nutrient Cycling'],
      'Biodiversity and Conservation': ['Patterns of Biodiversity', 'Loss of Biodiversity', 'Biodiversity Conservation'],
      'Environmental Issues': ['Air Pollution', 'Water Pollution', 'Solid Waste Management', 'Greenhouse Effect', 'Ozone Depletion'],
    },
  },
  [Subject.MATHEMATICS]: {
    class11: {
      'Sets': ['Types of Sets', 'Venn Diagrams', 'Operations on Sets'],
      'Relations & Functions': ['Cartesian Product', 'Domain & Range', 'Types of Functions'],
      'Trigonometric Functions': ['Angles', 'Trigonometric Functions', 'Trigonometric Equations'],
      'Principle of Mathematical Induction': ['Process of Induction'],
      'Complex Numbers and Quadratic Equations': ['Algebra of Complex Numbers', 'Argand Plane', 'Quadratic Equations'],
      'Linear Inequalities': ['Algebraic Solutions', 'Graphical Solutions'],
      'Permutations and Combinations': ['Fundamental Principle of Counting', 'Permutations', 'Combinations'],
      'Binomial Theorem': ['Expansion', 'General & Middle Terms'],
      'Sequence and Series': ['Arithmetic Progression', 'Geometric Progression', 'Special Series'],
      'Straight Lines': ['Slope of a Line', 'Forms of Equation of Line', 'Distance of Point from Line'],
      'Conic Sections': ['Circles', 'Parabola', 'Ellipse', 'Hyperbola'],
      'Introduction to Three Dimensional Geometry': ['Coordinate Axes', 'Distance Formula', 'Section Formula'],
      'Limits and Derivatives': ['Limits', 'Derivatives of Functions'],
      'Mathematical Reasoning': ['Statements', 'Logical Connectives', 'Implications'],
      'Statistics': ['Mean Deviation', 'Variance', 'Standard Deviation'],
      'Probability': ['Random Experiments', 'Events', 'Axiomatic Approach'],
    },
    class12: {
      'Relations and Functions': ['Types of Relations', 'Types of Functions', 'Composition of Functions', 'Invertible Function'],
      'Inverse Trigonometric Functions': ['Domain & Range', 'Properties'],
      'Matrices': ['Operations on Matrices', 'Transpose', 'Symmetric & Skew Symmetric', 'Invertible Matrices'],
      'Determinants': ['Properties', 'Area of Triangle', 'Adjoint & Inverse', 'Solution of System of Linear Equations'],
      'Continuity and Differentiability': ['Continuity', 'Differentiability', 'Derivatives of Composite Functions', 'Mean Value Theorem'],
      'Application of Derivatives': ['Rate of Change', 'Increasing/Decreasing Functions', 'Tangents & Normals', 'Maxima & Minima'],
      'Integrals': ['Indefinite Integrals', 'Definite Integrals', 'Properties of Definite Integrals'],
      'Application of Integrals': ['Area under Simple Curves', 'Area between Two Curves'],
      'Differential Equations': ['Order & Degree', 'General & Particular Solutions', 'Methods of Solving DE'],
      'Vector Algebra': ['Types of Vectors', 'Addition of Vectors', 'Scalar (Dot) Product', 'Vector (Cross) Product'],
      'Three Dimensional Geometry': ['Direction Cosines', 'Equation of Line', 'Plane', 'Angle between Lines/Planes'],
      'Linear Programming': ['Objective Function', 'Constraints', 'Graphical Method'],
      'Probability': ['Conditional Probability', 'Bayes\' Theorem', 'Random Variables', 'Bernoulli Trials'],
    },
  },
};

export const SUBJECTS_BY_EXAM: Record<ExamType, Subject[]> = {
  [ExamType.NEET]: [Subject.PHYSICS, Subject.CHEMISTRY, Subject.BIOLOGY],
  [ExamType.JEE]: [Subject.PHYSICS, Subject.CHEMISTRY, Subject.MATHEMATICS],
};